<a href="https://colab.research.google.com/github/Denys20233/university_machine_learning/blob/main/%D0%9F%D1%96%D0%B4%D0%B3%D0%B0%D0%B8%CC%86%D0%BD%D0%B8%D0%B8%CC%86_%D0%9B%D0%A0_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

## **Варіант 15**

### Завдання 1

15. Створіть одновимірний масив (вектор) з простими числами, не перевищуючи 70, та
виведіть його значення.

In [ ]:
vector = np.arange(1, 71)

print("Вектор чисел, які не перевищують 70:")
print(vector)

Вектор чисел, які не перевищують 70:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


### Завдання 2

15. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями
квадратів перших натуральних чисел.

In [ ]:
s = [i**2 for i in range(1, 10)]
a = np.array(s).reshape(3, 3)

print("Матриця 3x3 з квадратів перших натуральних чисел:")
print(a)

Матриця 3x3 з квадратів перших натуральних чисел:
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


### Завдання 3

15. Створіть масив розміром 5x5, заповніть його випадковими цілими числами від -10 до
10 та знайдіть максимальний елемент.

In [ ]:
a = np.random.randint(-10, 11, size=(5, 5))

print("Матриця:")
print(a)

max_value = np.max(a)
print("\nМаксимальний елемент матриці:", max_value)

Матриця:
[[ -3  -6  -2   6   8]
 [  1   6   8  -2   6]
 [ -6  -7   3   1   5]
 [  4   9  -2   6 -10]
 [ -9   2  -9   0   1]]

Максимальний елемент матриці: 9


### Завдання 4

15. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в
діапазоні від 0 до 1 та знайдіть вектор-рядок, що містить максимальні елементи в
кожному стовпці.

In [ ]:
a = np.random.rand(4, 4)

print("Матриця:")
print(a)

max_in_columns = np.max(a, axis=0)

print("\nВектор-рядок з максимальними елементами кожного стовпця:")
print(max_in_columns)

Матриця:
[[0.08805118 0.24133035 0.04382389 0.58978963]
 [0.82069279 0.24071248 0.0147757  0.76511564]
 [0.4400784  0.67192661 0.78526533 0.18554373]
 [0.80329352 0.28650229 0.9347969  0.06219488]]

Вектор-рядок з максимальними елементами кожного стовпця:
[0.82069279 0.67192661 0.9347969  0.76511564]


### Завдання 5

15. Створіть два одновимірних масиви розміром 7, заповніть їх випадковими цілими
числами в діапазоні від -10 до 10 та виконайте на них поелементні операції додавання,
віднімання та множення.

In [ ]:
arr1 = np.random.randint(-10, 11, 7)
arr2 = np.random.randint(-10, 11, 7)

add = arr1 + arr2
subt = arr1 - arr2
mul = arr1 * arr2

print("Масив 1:", arr1)
print("Масив 2:", arr2)
print("Додавання:", add)
print("Віднімання:", subt)
print("Множення:", mul)

Масив 1: [  3   6 -10   1   7   9   0]
Масив 2: [ 8 -3  6  3 -1  8  0]
Додавання: [11  3 -4  4  6 17  0]
Віднімання: [ -5   9 -16  -2   8   1   0]
Множення: [ 24 -18 -60   3  -7  72   0]


### Завдання 6

15. Створіть дві матриці 4x4, заповніть їх довільними цілими числами від -10 до 10 та
знайдіть їх добуток.

In [ ]:
a = np.random.randint(-10, 11, (4, 4))
b = np.random.randint(-10, 11, (4, 4))

print("A:\n", a, "\nB:\n", b, "\nA*B:\n", np.dot(a, b), "\n")

A:
 [[ 0  0 -9 -3]
 [-1 -9  5  0]
 [-6  2  7 -7]
 [ 2 -3 -8  8]] 
B:
 [[  9 -10  -5   8]
 [  5   2  -8   1]
 [  2  -6   4   4]
 [-10   7  -9   7]] 
A*B:
 [[ 12  33  -9 -57]
 [-44 -38  97   3]
 [ 40 -27 105 -67]
 [-93  78 -90  37]] 



### Завдання 7

15. Створіть дві матриці розміром 4x2 та 2x2, заповніть їх випадковими цілими числами
в діапазоні від 1 до 3 та перемножте їх між собою.

In [ ]:
a = np.random.randint(1, 4, (4, 2))
b = np.random.randint(1, 4, (2, 2))

print("A:\n", a, "\nB:\n", b, "\nA*B:\n", np.dot(a, b), "\n")

A:
 [[1 2]
 [1 1]
 [2 1]
 [3 2]] 
B:
 [[3 1]
 [1 2]] 
A*B:
 [[ 5  5]
 [ 4  3]
 [ 7  4]
 [11  7]] 



### Завдання 8

15. Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні
від 1 до 7 та знайдіть її обернену матрицю.

In [ ]:
a = np.random.randint(1, 8, (2, 2))
print("Матриця А:\n", a)

a_inv = np.linalg.inv(a)
print("\nОбернена матриця до матриці A:\n", a_inv)

Матриця А:
 [[3 3]
 [3 2]]

Обернена матриця до матриці A:
 [[-0.66666667  1.        ]
 [ 1.         -1.        ]]


### Завдання 9

15. Створіть матрицю розміром 3x5, заповніть її випадковими цілими числами в діапазоні
від 0 до 1 та транспонуйте її.

In [ ]:
m = np.random.rand(3, 5)
print("Матриця:\n", m)
transposed = m.T

print("\nТранспонована матриця:\n", transposed)

Матриця:
 [[0.83087641 0.2101072  0.89491684 0.22824093 0.95860268]
 [0.34809483 0.64970082 0.08254884 0.4194874  0.165938  ]
 [0.27355704 0.24098553 0.12330926 0.3207809  0.51505662]]

Транспонована матриця:
 [[0.83087641 0.34809483 0.27355704]
 [0.2101072  0.64970082 0.24098553]
 [0.89491684 0.08254884 0.12330926]
 [0.22824093 0.4194874  0.3207809 ]
 [0.95860268 0.165938   0.51505662]]


### Завдання 10

15. Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю
випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в
діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

In [ ]:
m = np.random.rand(3, 4)
v = np.random.randint(1, 11, (4, 1))

print("Матриця:")
print(m)

print("\nВектор:")
print(v)

product = np.dot(m, v)

print("\nДобуток матриці на вектор:")
print(product)

Матриця:
[[0.42493135 0.27491416 0.57118146 0.71967599]
 [0.00348961 0.01559113 0.67069457 0.94901961]
 [0.97590183 0.02455253 0.39894626 0.69795708]]

Вектор:
[[ 4]
 [ 6]
 [10]
 [ 1]]

Добуток матриці на вектор:
[[9.78070093]
 [7.76347053]
 [8.73834225]]


### Завдання 11

15. Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю
випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами
від 0 до 1, і знайдіть суму елементів матриці, які менше за відповідний елемент
вектору.

In [ ]:
m = np.random.rand(2, 3)
v = np.random.rand(3, 1)

print("Матриця:")
print(m)

print("\nВектор:")
print(v)

mask = m < v.T
sum_elements = np.sum(m[mask])

print("\nСума:", sum_elements)

Матриця:
[[0.19299682 0.74082065 0.10515234]
 [0.44082489 0.0733652  0.15760551]]

Вектор:
[[0.40650809]
 [0.69381691]
 [0.73231705]]

Сума: 0.5291198779324708


### Завдання 12

15. Створіть дві матриці розміром 8x8, заповніть їх випадковими цілими числами в
діапазоні від 1 до 10 та знайдіть їхню суму.

In [ ]:
a = np.random.randint(1, 11, (8, 8))
b = np.random.randint(1, 11, (8, 8))
print("A:\n", a, "\nB:\n", b)

print("\nСума матриць А та В:\n", a+b)

A:
 [[ 7 10 10  2  1  2 10  6]
 [ 2  3  6  9  7  2 10  1]
 [ 3  1 10  3 10  6  1  1]
 [10  3  3  8 10  4  6  3]
 [10  6  1  3  5  5  1  4]
 [ 5  9  1 10  3  4  1  6]
 [ 4  9 10  6  4  9  6 10]
 [ 1  3  9 10  5 10  2  6]] 
B:
 [[ 4  3 10  3  4  3  9  7]
 [ 4  1  2  9  4  3  8 10]
 [10  2  8  6  8 10  3  6]
 [10 10  7  1  5  7  4  2]
 [ 1  1  4  6  9  9 10  1]
 [ 7  8  6  6  1  5  6  2]
 [10  4  3  9  1  9  9  2]
 [ 7  3  1 10 10  4 10  6]]

Сума матриць А та В:
 [[11 13 20  5  5  5 19 13]
 [ 6  4  8 18 11  5 18 11]
 [13  3 18  9 18 16  4  7]
 [20 13 10  9 15 11 10  5]
 [11  7  5  9 14 14 11  5]
 [12 17  7 16  4  9  7  8]
 [14 13 13 15  5 18 15 12]
 [ 8  6 10 20 15 14 12 12]]


### Завдання 13

15. Створіть дві матриці розміром 3x3, заповніть їх випадковими дійсними числами в
діапазоні від -1 до 1 та знайдіть добуток їх елементів.

In [ ]:
a = np.random.uniform(-1, 1, (3, 3))
b = np.random.uniform(-1, 1, (3, 3))

print("Перша матриця:")
print(a)

print("\nДруга матриця:")
print(b)

product_matrix = a * b

print("\nДобуток відповідних елементів матриць:")
print(product_matrix)

Перша матриця:
[[-0.73652444  0.50375695  0.11855607]
 [ 0.04481288 -0.41816389  0.3046771 ]
 [-0.7621621  -0.13040985  0.79866163]]

Друга матриця:
[[ 0.46632154  0.29373115  0.36946013]
 [ 0.56083615  0.62765076  0.74114764]
 [-0.81431399  0.47600199  0.16097522]]

Добуток відповідних елементів матриць:
[[-0.34345721  0.14796911  0.04380174]
 [ 0.02513268 -0.26246088  0.22581071]
 [ 0.62063926 -0.06207535  0.12856473]]


### Завдання 14

15. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
діапазоні від -5 до 5 та знайдіть добуток елементів матриці, які більше за їх середнє
арифметичне значення.

In [ ]:
m = np.random.uniform(-5, 5, (3, 3))

print("Матриця:")
print(m)

mean_value = np.mean(m)
print("\nСереднє арифметичне матриці:", mean_value)

elements_above_mean = m[m > mean_value]
print("\nЕлементи матриці, більші за середнє:", elements_above_mean)

product = np.prod(elements_above_mean)
print("\nДобуток елементів, більших за середнє:", product)

Матриця:
[[ 0.29306038 -1.06634469 -3.81213283]
 [ 2.46604501 -3.63579196 -3.18191919]
 [-3.27738501 -3.4738574   4.12931588]]

Середнє арифметичне матриці: -1.284334423032684

Елементи матриці, більші за середнє: [ 0.29306038 -1.06634469  2.46604501  4.12931588]

Добуток елементів, більших за середнє: -3.182246548524109


### Завдання 15

15. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
діапазоні від -0.5 до 0.5 та знайдіть вектор-стовпчик, що містить найбільше за модулем
ціле значення в кожному рядку матриці.

In [ ]:
m = np.random.uniform(-0.5, 0.5, (3, 3))
print("Матриця:\n", m)

rounded_matrix = np.rint(m).astype(int)
print("\nМатриця, округлена до цілих чисел:")
print(rounded_matrix)

max_abs_vector = np.array([row[np.argmax(np.abs(row))] for row in rounded_matrix]).reshape(3, 1)

print("\nВектор-стовпчик з найбільшими за модулем цілими числами по рядках:")
print(max_abs_vector)

Матриця:
 [[-0.00385505 -0.16046542 -0.18541088]
 [ 0.49338067  0.33977377  0.18220889]
 [ 0.15391243  0.43527412  0.45773597]]

Матриця, округлена до цілих чисел:
[[0 0 0]
 [0 0 0]
 [0 0 0]]

Вектор-стовпчик з найбільшими за модулем цілими числами по рядках:
[[0]
 [0]
 [0]]
